#!/usr/bin/python3
number = 3.14159
year = 202
# YOUR CODE GOES HERE. PLEASE REMOVE THIS LINE
print(f"float {number: .2f}")

print(f"Hello {year=}")
print(f"Hello {year:,}")
print(f'Hello {year:0<4}')
